# Overview

name: github-actions

on: [push] # action
jobs:
  build: # job name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # clone our repository to the GitHub runner
      - uses: actions/setup-java@v3 # install Java 17
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          gradle-version: 7.5
      # - run: java --version
      # - run: chmod +x app/gradlew
      - run: make -C app build
      - run: make -C app test
      - run: make -C app lint