# Overview

name: github-actions

on: [push] # action
jobs:
  build: # job name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # clone our repository to the GitHub runner
      - uses: actions/setup-java@v3 # install Java 17
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          gradle-version: 7.5
          build-root-directory: app
          
      - run: chmod +x app/gradlew
      - run: make -C app build
      - run: make -C app test
      - run: make -C app lint

      - name: Test & publish code coverage
        # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v3.2.0
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          JACOCO_SOURCE_PATH: app/src/main/java
        with:
          coverageCommand: make test-report
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
            