# Overview

name: github-actions 🚀

on: [push] # action
jobs:
  build: # job name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # clone our repository to the github runner
      - run: make -C app test
      - run: make -C app lint
